### ISSUE TITLE
The behaviour of urlfetch of Google App Engine will be changed from April 2015. Will it have any impact on simpleauth

### ISSUE THREAD

**Issue by kongakong** [x1ddos/simpleauth#38]
Here is the content of the GAE announcement

"Dear URL Fetch users,

We’re contacting you because you’re listed as the administrator for your organization’s App Engine application, which uses the URL Fetch service. During the phased rollout of an update to this service, we determined that your application may be affected by the change described below.

Currently, the URL Fetch service preserves your original HTTP method (e.g., GET, POST) when it receives and responds to a 302 Moved Temporarily response. Modern user agents typically issue a GET request in response to a 302. After the update, URL Fetch will only issue a GET request after receiving a 302 response, rather than preserving the original method. This may cause requests to be routed differently and/or return 404s or other errors, and will drop the message body from POST requests.

To avoid being affected by this change, please verify that either:
Your app sends non-GET requests (such as POST) directly to the final URL that will handle the request rather than to one that redirects. Some common services, including App Engine, use 302 to redirect HTTP connections to HTTPS and vice versa, so it’s important to check that your protocol is correct as well. You can use the final_url field of the Response object (or a similar object in other APIs) to determine if your fetches are being redirected.
The destination server sends a 303 or 307 HTTP code, each of which specifies the redirect behavior with respect to HTTP methods, rather than a 302.

We will apply the update to your affected application’s URL Fetch usage on April 25, 2015.

If you have any questions, please contact our support team - even if you do not have a support contract.

Sincerely,
Google Cloud Platform team "

**Comment by x1ddos** [comment]
I'm pretty sure simpleauth wasn't affected. If it is, please open an issue with details (provider, endpoint, etc)
