### ISSUE TITLE
Facebook deprecated v2.2 of its api on the 27th March which breaks simpleauth

### ISSUE THREAD

**Issue by pceccato** [x1ddos/simpleauth#43]
from the documentation.

[Oauth Access Token] Format - The response format of https://www.facebook.com/v2.3/oauth/access_token returned when you exchange a code for an access_token now return valid JSON instead of being URL encoded. The new format of this response is {"access_token": {TOKEN}, "token_type":{TYPE}, "expires_in":{TIME}}. We made this update to be compliant with section 5.1 of RFC 6749.

**Comment by pceccato** [comment]
I have submitted a pull request with a proposed fix.

**Comment by x1ddos** [comment]
Fixed by https://github.com/x1ddos/simpleauth/commit/4ce8b8108a4742a872e4695c118945612ca007eb
