### ISSUE TITLE
Facebook authentication has stopped working (see your demo for the erro)

### ISSUE THREAD

**Issue by slrsoft** [x1ddos/simpleauth#47]
Facebook authentication has stopped working on our production site - it is also not working on your demo site ( https://simpleauth.appspot.com/ ) - any idea what the problem is?
Thanks

**Comment by x1ddos** [comment]
@slrsoft it should be fixed by https://github.com/x1ddos/simpleauth/pull/44 but I haven't pushed a release yet. Use the version at HEAD.

**Comment by slrsoft** [comment]
ok thanks

**Comment by x1ddos** [comment]
Sorry about that! Maybe I should've posted something on the simpleauth
google group.

Am 30.03.2017 2:16 nachm. schrieb "slrsoft" <notifications@github.com>:
