### ISSUE TITLE
Google+ API is deprecated and simpleauth needs to use the new Google Sign In

### ISSUE THREAD

**Issue by markuso** [x1ddos/simpleauth#49]
Any plans or ideas on modifying `simpleauth` to stop using Google+ API and use their latest API? It is shutting down in a few weeks and `simpleauth` will start failing.

Here is the Google link to the announcement:
https://developers.google.com/+/api-shutdown

**Comment by markuso** [comment]
After pending time solving this today, I was able to modify `simpleauth` to use the latest Google authentication endpoints, and have submitted a pull request of the changes. I have tested this in production already and it works perfectly.

Just know that the `userinfo` data that comes back from Google has the properties `link` and `id`, instead of the old version `profile` and `sub`.

**Comment by pceccato** [comment]
Thanks for highlighting this issue and fixing it!

**Comment by x1ddos** [comment]
Fixed by #50.
